plugins = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\NickW\\Claude\\Service Desk Continual Improvement\\frontend\\dist"
publishOrigin = "config"
commandOrigin = "config"
base = "C:\\Users\\NickW\\Claude\\Service Desk Continual Improvement\\frontend"
command = "npm install && npm run build"

[build.environment]
NODE_VERSION = "22"
VANTAGE_BASE = "/"
VITE_API_BASE = "https://pi5.tailecb90f.ts.net/vantage/api"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Robots-Tag = "noindex, nofollow"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer"
X-Frame-Options = "DENY"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]